// <auto-generated />
using System;
using MainDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MainDbContext.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Models.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Development"
                        });
                });

            modelBuilder.Entity("Models.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Name = "Mohamed"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Name = "Ahmed"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 1,
                            Name = "Sarah"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 2,
                            Name = "Nahla"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 2,
                            Name = "Hanaa"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 2,
                            Name = "Soaad"
                        });
                });

            modelBuilder.Entity("Models.Models.EmployeeReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeRate")
                        .HasColumnType("int");

                    b.Property<int?>("ReviewedEmployeeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ReviewedEmployeeId");

                    b.ToTable("EmployeeReviews");
                });

            modelBuilder.Entity("Models.Models.Employee", b =>
                {
                    b.HasOne("Models.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Models.Models.EmployeeReview", b =>
                {
                    b.HasOne("Models.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.HasOne("Models.Models.Employee", "ReviewedEmployee")
                        .WithMany()
                        .HasForeignKey("ReviewedEmployeeId");

                    b.Navigation("Employee");

                    b.Navigation("ReviewedEmployee");
                });
#pragma warning restore 612, 618
        }
    }
}
